tools:
  exceptions: 
    frontend: https://sentry.io/organizations/dcsil/issues/?project=5662565
    backend: https://sentry.io/organizations/dcsil/issues/?project=5603815 
  logging: ./app.log
  ci:
    frontend: https://github.com/dcsil/Moguls-Analysis/blob/master/.github/workflows/front-end.yml
    backend: https://github.com/dcsil/Moguls-Analysis/blob/master/.github/workflows/python-app.yml

services:
  production: https://moguls-analysis.herokuapp.com/

docs:
  getting_started: https://github.com/dcsil/Moguls-Analysis
  
commands:
  bootstrap: script/bootstrap
  database: https://cloud.mongodb.com/v2/60346be4c3b9857881e2b62d#clusters/detail/491
  server: python3 app.py
  test: script/run_tests