# This is a basic workflow to help you get started with Actions

name: Front-end CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
      shell: bash

    - uses: actions/cache@v2
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-npde-${{ hashFiles('**/package-lock.json') }}

    - name: client npm install and build
      working-directory: ./client
      run: |
        npm install
        npm run build --if-present
      env:
        CI: true
        
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: a1cf48d9b677a7775d2ccbfb4bd56f332069471e183ecfff191f48286c02a3a1
      with:
        coverageCommand: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
        coverageLocations: coverage/lcov.info:lcov
        workingDirectory: ./client
