# This is a basic workflow to help you get started with Actions

name: Front-end CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: client npm install, build, and test
      working-directory: ./client
      run: |
        npm install
        npm run build --if-present
        npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      env:
        CI: true
